// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSqHuiDq4g-G2mUac3JJzc1XBWXRJbHs',
    appId: '1:156715072370:web:cf244c43e27fb4b86efbeb',
    messagingSenderId: '156715072370',
    projectId: 'dase-77989',
    authDomain: 'dase-77989.firebaseapp.com',
    storageBucket: 'dase-77989.appspot.com',
    measurementId: 'G-G00P9034GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43KwC7-ErOOfaZ0o0eP8PDSG2UikNFlA',
    appId: '1:156715072370:android:adea78ec5594e1fe6efbeb',
    messagingSenderId: '156715072370',
    projectId: 'dase-77989',
    storageBucket: 'dase-77989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLwWI_GahkzoPaZA6BEt1A9m2QHcBfat0',
    appId: '1:156715072370:ios:898f505d00966f5e6efbeb',
    messagingSenderId: '156715072370',
    projectId: 'dase-77989',
    storageBucket: 'dase-77989.appspot.com',
    iosClientId: '156715072370-6bud712bmje2lue9na7s5h2uqb25k3at.apps.googleusercontent.com',
    iosBundleId: 'com.dasegroup.daseBackoffice',
  );
}
